version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
    - requirements: docs/requirements.txt  # Install only necessary documentation dependencies

sphinx:
  configuration: docs/source/conf.py  # Ensure correct configuration path
