[tool.isort]
profile = "black"
line_length = 160
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
skip_gitignore = true
force_grid_wrap = 0
combine_as_imports = true
known_first_party = ["your_project_name"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"] 