name: Pre-Commit Linting

on:
  push:
    branches: ['**']  # Runs on all branches when pushing
  pull_request:
    branches: ['**']  # Runs on all PRs
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      

      - name: Install pre-commit and dependencies
        run: |
          pip install pre-commit black isort flake8

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
